### ISSUE TITLE
formatter does not work on focus lost and up/down

### ISSUE THREAD

**Issue by Samnan** [react-component/input-number#110]
I have created a simple component using rc-input-number, render() as below

```
render() {
    return ((
      <div className="number-input">
        <InputNumber
          onChange={this.onChange}
          onKeyDown={this.onKeyDown}
          formatter={value => `${formatNumberToString(value)}`}
        />
      </div>
    ));
  }

```

```
// makes only number input possible and avoid all alphabets etc
onKeyDown(e) {
    const { keyCode } = e;
    // backspace / delete key / tab key
    if (keyCode === 8 || keyCode === 46 || keyCode === 9) {
      return true;
    }

    // arrow keys
    if (keyCode > 36 && keyCode < 41) {
      return true;
    }
    // allow number keys
    if (keyCode > 47 && keyCode < 58) {
      return true;
    }

    // allow only one dot in number
    if (keyCode === 190) {
      if (this.state.value.indexOf('.') === -1) {
        return true;
      }
    }

    e.preventDefault();
    return false;
  }

```
where formatNumberToString() adds thousand separator comma to the number simply.

It works nicely when i change the number in component using number keys, but as soon as the focus is lost, the value in component displays without commas. Focusing again does not show commas, until i press a key to change the value. Also pressing up and down keys when the input is empty causes the number to changes, but again no commas appear until i press a key to input directly. 

Using latest 4.0.12 in react project.

Any help appreciated... what am I doing wrong?

**Comment by zombieJ** [comment]
What's the code of `formatNumberToString`?

**Comment by Samnan** [comment]
@zombieJ 

```
const options = {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2
  };
  return Number(num).toLocaleString(undefined, options);
```

**Comment by zombieJ** [comment]
I can't reproduce it. Could you provide the gif of snapshot? https://codesandbox.io/s/j3xrkvnjr5
![kapture 2018-07-18 at 12 01 42](https://user-images.githubusercontent.com/5378891/42858699-5fd037e2-8a82-11e8-9bef-f3a1df82a88d.gif)

**Comment by Samnan** [comment]
@zombieJ  here is a sandbox with exact code as i have
https://codesandbox.io/s/5xpkw2xwyk
however on the sandbox the separator shows correctly but decimal places do not work
same code on my local machine has the problem as i mentioned earlier..

is this related to some dependency on react?

**Comment by Samnan** [comment]
how it works on my machine (same browser as the sandbox tested on, please note)

![bug](https://user-images.githubusercontent.com/872992/42861136-31bcd31a-8a73-11e8-839a-0232cd299320.gif)

**Comment by zombieJ** [comment]
What's your browser and version?

**Comment by Samnan** [comment]
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by zombieJ** [comment]
You may adjust the sandbox code to reproduce as your snapshot or I can't find what happen : (

**Comment by Samnan** [comment]
@zombieJ I will try that.

**Comment by Samnan** [comment]
Ok I seem to have fixed it. Had to do a clean start, not sure what was the issue, but it looks like the problem is gone in my project.

@zombieJ  thanks for your help!
