### ISSUE TITLE
Input NUMBER

### ISSUE THREAD

**Issue by ali-master** [react-component/input-number#113]
Hi there,

When we are talking about input number type, then we should have just an input number without typing any other strings except number, right?

So if the user tries to type anything, then we should validate the value and prevent to type anything except the number. Because it can help users to validate forms contents.

https://github.com/react-component/input-number/blob/ffdd76e78dccb6649b520ed4be14451ad6a88924/src/index.js#L242

**Comment by zombieJ** [comment]
Since input-number support format / parser, this check is after user input: http://react-component.github.io/input-number/examples/formatter.html
