### ISSUE TITLE
Consider step and precision as two different props.

### ISSUE THREAD

**Issue by HyczZhu** [react-component/input-number#13]
Right now the precision of the input number is controlled by the step property. Say if I input a number 10.11 to an input-number with step equals to 1, the number will be changed to 10, although 10.11 is a very valid number.

So the only way to allow me to input 10.11 is to set step to 0.01 which is not very useful indeed. Sometimes we want to make 10.11 a valid value and at the meantime set step to 1.

How about adding a new property precision to solve this problem?

**Comment by janeluck** [comment]
It will be complicated. Check htmlElement `input type='number'` and you will find the same thing.
