### ISSUE TITLE
手动在 input 输入值后，点+-不按照输入的值为基准进行

### ISSUE THREAD

**Issue by warmhug** [react-component/input-number#25]
另外手动输入值，为什么不触发 onChange 事件？

**Comment by silentcloud** [comment]
初步看了哈，貌似是 onChange 的时候，没有 setState({value)

**Comment by afc163** [comment]
https://github.com/react-component/input-number/blob/master/src/mixin.js#L180

这里应该优先去拿 this.state.inputValue 。

**Comment by silentcloud** [comment]
我本地试了哈，这样貌似也能解决问题：
```
  setInputValue(v) {
    this.setState({
      value: v,
      inputValue: v,
    });
  },
```

**Comment by afc163** [comment]
别，PC 端需要允许输入任意字符，blur 时检查是否数字并触发 onChange。

**Comment by silentcloud** [comment]
@afc163 恩，你给出的方案比较合适，我 check 一下 rn 的看看是否 ok

**Comment by silentcloud** [comment]
https://github.com/react-component/input-number/pull/26 check 一下， 发个版本? @afc163

**Comment by afc163** [comment]
已发。
