### ISSUE TITLE
InputNumber set precision bug 

### ISSUE THREAD

**Issue by 93336406** [react-component/input-number#257]
![73A83E99-8F7C-4AF0-9AEE-22B3ED98211F](https://user-images.githubusercontent.com/23730744/88499361-2ce0f200-cff8-11ea-999e-4aa069d6d623.png)

when  the precision is set to 2, and give defaultValue is 123456789123456.47,after losing focus, the decimal part of the input box value cannot be displayed correctly,please look at the attch files of view

**Comment by 07akioni** [comment]
Your value exceeds Number.MAX_SAFE_INTEGER.

**Comment by 07akioni** [comment]
Precision is the digit count after dot. You may want to use `step`.
