### ISSUE TITLE
No option to attatch custom className on the input

### ISSUE THREAD

**Issue by sharvit** [react-component/input-number#261]
I would like to set a custom class on the input field so I can integrate it with bs3 by adding the `form-control` class.

It would be nice to have a `inputClassName` prop so I can add my own class-name.

Thanks!

**Comment by hperezs** [comment]
Was this feature ever considered? We ran into the same issue. For now, we used Sass to extend `.form-control` but we think the library should support a custom class name in the props.

Thanks

**Comment by yoyo837** [comment]
Using classNames.input https://github.com/react-component/input-number/pull/570 Does it meet your requirements?

**Comment by yoyo837** [comment]
Trace in https://github.com/react-component/input-number/issues/594
