### ISSUE TITLE
无法指定input的类型，

### ISSUE THREAD

**Issue by eaTong** [react-component/input-number#28]
如题：希望得到的效果是输入：`<InputNumber type='number'>`，能得到`<inupt type="number"/>`的输出，之前的版本貌似还可以，但是现在的版本不行。。。

**Comment by benjycui** [comment]
完全看不懂你的需求。

**Comment by eaTong** [comment]
哈哈， 我的失误，没有预览一下效果，里面的代码段直接没显示出来。。。

**Comment by benjycui** [comment]
这个 type 的设置没意义吧。

**Comment by eaTong** [comment]
有啊，如果放在手机端的话可以默认调出数字键盘啊，虽然只是个很小的优化，但是个人感觉放在在手机端还是很实用的。

**Comment by benjycui** [comment]
@eaTong 来个 PR 把 type 补上吧。。

现在只能缺一个补一个了。

**Comment by eaTong** [comment]
已提交，本想根据原本的代码直接增加`{...props}`，但是由于不知道删除这行代码的具体情况，所以只是增加了一行：`type={props.type}`
