### ISSUE TITLE
step为小数时，希望显示的数字一直保留小数的位数

### ISSUE THREAD

**Issue by zengyue** [react-component/input-number#30]
比如step={0.01},  当从`1.09` 加0.01时，希望显示的是`1.10`，但是现在显示的是`1.1`

**Comment by eaTong** [comment]
是不是要输入到具体位数之后才一直保留？因为现在出现这种情况：刚输入第一个数字的时候里面就变成多位小数了，比如step={0.0001}的时候，输入：1，值立马变为：1.0000，这样感觉像是Bug
