### ISSUE TITLE
ANTD can no longer resolve module

### ISSUE THREAD

**Issue by atomic-tang** [react-component/input-number#310]
Just checked the package on npm website and there was a recent publish. I am now getting a "Cannot find module" error when installing dependencies for my antd project. 

`Cannot find module '/node_modules/rc-input-number/lib/index'. Please verify that the package.json has a valid "main" entry`

I checked the node modules folder and the lib folder for rc-input-number is missing after installing antd.

**Comment by yoyo837** [comment]
Please check your installation logs.

**Comment by atomic-tang** [comment]
@yoyo837 The issue is now resolved. Did something happen to the repository?

**Comment by yoyo837** [comment]
We did nothing just now.

**Comment by afc163** [comment]
rc-input-number@4.5.8 is a broken version, fixed in `rc-input-number@4.5.9`, please reinstall node_modules.

**Comment by codeZyb** [comment]
me too

**Comment by yoyo837** [comment]
The 4.5.9 version cannot be seen in npm. @afc163

**Comment by afc163** [comment]
https://www.npmjs.com/package/rc-input-number/v/4.5.9

**Comment by yoyo837** [comment]
Can we deprecate version 4.5.8 in/on npm?

**Comment by afc163** [comment]
Done.
