### ISSUE TITLE
通过tab键让inputNumber失去焦点，导致onKeyUp没有触发，userTypingRef.current值没有重置为false。外部再进行赋值的时候会导致值不会发生改变

### ISSUE THREAD

**Issue by taoxhsmile** [react-component/input-number#317]
通过tab键让inputNumber失去焦点，导致onKeyUp没有触发，userTypingRef.current值没有重置为false。外部再进行赋值的时候会导致值不会发生改变

**Comment by yoyo837** [comment]
有复现吗？意思是tab键不触发 onKeyUp事件？

**Comment by taoxhsmile** [comment]
最新版本都存在这个问题可以复现，我搞一个demo

**Comment by yoyo837** [comment]
确实：onKeyDown 不阻止默认行为，就不会触发onKeyUp。

**Comment by taoxhsmile** [comment]
https://codesandbox.io/s/kind-kowalevski-qttqz?file=/src/App.js
