### ISSUE TITLE
step为小数时会导致无法正确输入数字

### ISSUE THREAD

**Issue by eaTong** [react-component/input-number#32]
当step为小数（0.0001）时，输入第一个数字之后值会变为：1.0000，且光标立马跑到最后，意味着如果我想输入：1234.5678的时候必须时刻将光标移到指定位置才能继续输入。
貌似是因为：[#30](https://github.com/react-component/input-number/issues/30)中要求强制保证小数位数导致的，是否考虑换成：输入的时候不强制规定位数，点击 + -按钮的时候才规定小数位数？
查看代码后发现有inputValue和value两个值，点击+-按钮时两个值相同，输入的时候不同，所以可以通过state中这两个值是否相等来判断是否需要返回相应位数的数据。

**Comment by eaTong** [comment]
已PR，望考虑 [PR #33 ](https://github.com/react-component/input-number/pull/33)

**Comment by afc163** [comment]
我看看。

**Comment by afc163** [comment]
感谢反馈和 PR ~
