### ISSUE TITLE
支持千位逗号问题

### ISSUE THREAD

**Issue by Dio-Zhu** [react-component/input-number#34]
本想自定义实现千分位逗号问题，如文本显示：“9,999.001”，实际form取值后为9999.001，但是由于源码里面有toNumber方法强制处理了，导致无法在文本框内正常处理显示“9,999.001”，能否提供下解决办法。

**Comment by afc163** [comment]
暂不支持，建议自行用 <input type="number" /> 进行封装。

**Comment by benjycui** [comment]
[react-maskedinput](https://github.com/insin/react-maskedinput)
