### ISSUE TITLE
组件的加减不能计算浮点数

### ISSUE THREAD

**Issue by zengyue** [react-component/input-number#35]
现在加减是浮点运算，浮点加减后的value很容易产生精度问题，导致获取的value不准确

**Comment by afc163** [comment]
最好给个例子。

**Comment by dead-horse** [comment]
@afc163 例如 3.01 经过3次减少之后应该是变成 2.98，但是结果是 2.97999999999999

stepper 需要考虑只对整数做加减，至于具体的精度位数让调用者自己来处理，否则要引入 bigNumber 之类的库才能解决了

**Comment by yiminghe** [comment]
precision={2}

3.01-0.01 = (300-1)/100

**Comment by dead-horse** [comment]
除100也不行，好像也有场景会出现小数

**Comment by dead-horse** [comment]
只能换成字符串

**Comment by afc163** [comment]
https://github.com/react-component/input-number/blob/948d840ebe41aa3ebc5843323aa5e6300bfe516c/src/mixin.js#L158

原来考虑到了，有处理的，但是还是有问题。

我再加个 toFixed。

**Comment by afc163** [comment]
rc-input-number@2.8.7
