### ISSUE TITLE
android 下长按「+/-」后并移出inputHandler后，离开手势，会一直进行加减，永远不会停止

### ISSUE THREAD

**Issue by zengyue** [react-component/input-number#37]
这个应该是android 下 touchstart并滑动手势后，就不会触发touchend 事件引起的

**Comment by afc163** [comment]
来个 PR 吧，没有调试环境。

**Comment by silentcloud** [comment]
跟这个有些许关联  https://github.com/ant-design/ant-design-mobile/issues/785

**Comment by benjycui** [comment]
@zengyue 解决方案应该和这个类似 https://github.com/react-component/input-number/pull/21

**Comment by paranoidjk** [comment]
@zengyue 的确是 touchend 不触发，加上 event.preventDefault() 也没用，有什么建议吗？

http://stackoverflow.com/questions/2987706/touchend-event-doesnt-work-on-android

**Comment by warmhug** [comment]
标注下 Android 什么版本？现在的 Android 7 和新的 chrome 没测出这个问题。

**Comment by paranoidjk** [comment]
@warmhug Android 7可能修复了，试下低版本的android，我这边是在小米4上测的

**Comment by warmhug** [comment]
android 4.1 的模拟器里 自带的浏览器上 也没测出问题

**Comment by aizigao** [comment]
同样的问题，发现达到最小和最大值的时候，记时器根本停不下来
![2017-08-21 11 49 54](https://user-images.githubusercontent.com/14126445/29503073-54de2008-8667-11e7-98bc-b3bca7a8dbc2.gif)

**Comment by benjycui** [comment]
@paranoidjk https://github.com/react-component/input-number/blob/master/src/index.ios.js#L158

个人猜测是在 `this.onPressOutUp` 被调用前，就因为`(editable && !upDisabledStyle)` 已经达到了边界，所以最终在用户 `onPressOut` 时并没有绑定事件 `undefined`。你可以排查下看看？

**Comment by yesmeck** [comment]
RN version has extracted to https://github.com/react-component/m-input-number.

https://github.com/react-component/m-input-number/issues/3
