### ISSUE TITLE
Bug(RN) : timer not clean， cause infinite loop

### ISSUE THREAD

**Issue by paranoidjk** [react-component/input-number#42]
click down to min value,  or click up to max value  will both cause this problem

Below is the reproduce steps:

1. assume we click the plus button util to the max value ,  the problem will occur at the last click
3. during `onPressIn` ,  we  do `value + 1`， and set a timer,  then  => `rerender`
4. during re render,  [this code](https://github.com/react-component/input-number/blob/master/src/index.ios.js#L126) canceled `onPressOut` event (**for disabled style**)
5. but because of there is no `onPressOut`, the timer set at step 2 will not be cancel, it will infinite set a new timer

**Comment by paranoidjk** [comment]
in a way， it's similar to this https://github.com/ant-design/ant-design-mobile/pull/832 ,
both because rerender canceled a event callback which shold be done

**Comment by paranoidjk** [comment]
@silentcloud 你要fix这个吗？

**Comment by silentcloud** [comment]
这个确认问题了，是连续点按的时候，settimeout 延迟太小，造成的，speed 改大一点就 ok 了，我提个 pr 修复一下

**Comment by paranoidjk** [comment]
@silentcloud 猜也是这种问题，但这种常量不太好搞，大了影响体验，小了出问题，比如你看这个 https://github.com/ant-design/ant-design-mobile/pull/832

**Comment by silentcloud** [comment]
测试了一下，这个改到 200 没太到影响，反而能让用户看清持续变化的当前值是多少

**Comment by paranoidjk** [comment]
ok，我也是改到200了，12 帧
