### ISSUE TITLE
Support currency amounts input

### ISSUE THREAD

**Issue by reid3290** [react-component/input-number#44]
I think supporting currency amounts input with automatically formatting will be very useful, like https://www.npmjs.com/package/react-currency-input.

**Comment by acomito** [comment]
I need this too. I'm using antd itself rather than this stand alone package though.

**Comment by paranoidjk** [comment]
- If you just need to show specific type of number,  you can use `props.formatter `
- If you want `currency input ` component which have some logic itself,  i suggest you use `rc-input-number` to build your own component.

**Comment by Attrash-Islam** [comment]
I'd like to work on this. What currency input means? ',' separator in thousands? Number with currency unit '$'?
