### ISSUE TITLE
Cannot build production version with using Ant Design

### ISSUE THREAD

**Issue by Seasle** [react-component/input-number#471]
After updating to 7.3.7 (#470), we get the following message when building in production:

```
Interface 'InputNumberProps<T>' incorrectly extends interface 'Omit<InputHTMLAttributes<HTMLInputElement>, "value" | "defaultValue" | "onChange" | "onInput">'.
  Types of property 'max' are incompatible.
    Type 'T | undefined' is not assignable to type 'string | number | undefined'.
      Type 'T' is not assignable to type 'string | number | undefined'.
        Type 'ValueType' is not assignable to type 'string | number | undefined'.
          Type 'null' is not assignable to type 'string | number | undefined'.
```

Environment:

- React: 17.0.2
- Ant Design: 4.22.8
- TypeScript: 4.7.4

**Comment by Shawn-Cui** [comment]
Is there any solution? @Seasle

**Comment by Shawn-Cui** [comment]
> 

I see, thx.

**Comment by fnimick** [comment]
To be clear: this only occurs in library development with strict mode on, but does occur in client projects with strict mode enabled.

**Comment by afc163** [comment]
@li-jia-nan

**Comment by fnimick** [comment]
This should be resolved by https://github.com/react-component/input-number/issues/481

**Comment by li-jia-nan** [comment]
> @li-jia-nan

- #482

**Comment by afc163** [comment]
https://github.com/react-component/input-number/pull/482
