### ISSUE TITLE
Selection/focus issue on IE 10

### ISSUE THREAD

**Issue by mamapitufo** [react-component/input-number#58]
When you have 2 `InputNumber` next to each other, both with a value, and you try to tab between them on IE 10, the app will get stuck selecting the values and focusing between the inputs.

This works just fine on a recent version of Chrome.

This is the code I used to reproduce the issue on a vanilla `create-react-app` project (in `App.js`):

```
import React, { Component } from 'react'
import InputNumber from 'rc-input-number'
import 'rc-input-number/assets/index.css'

class App extends Component {
  render() {
    return (
      <div>
        <InputNumber defaultValue={3}/>
        <InputNumber defaultValue={4}/>
      </div>
    )
  }
}

export default App
```

Once you have the app running, select the value on the first input and hit Tab. The selection and focus should start jumping from one field to the other and the app will be stuck in a loop.

**Comment by afc163** [comment]
Try `3.4.7`

**Comment by afc163** [comment]
I reproduced it.

**Comment by mamapitufo** [comment]
The fix works like a charm, thank you!
