### ISSUE TITLE
Changing value onBlur when out of range is an accessibility issue

### ISSUE THREAD

**Issue by mellis481** [react-component/input-number#591]
Changing the value of an input number field onBlur is a huge accessibility issue as some users (eg. blind users) will have a value they entered change unbeknownst to them.

Would a PR be accepted that allows consumers to opt-out of [this](https://github.com/react-component/input-number/blob/master/src/InputNumber.tsx#L305-L312) functionality? Perhaps the optional boolean prop could be called `shouldCorrectRangeIssue`. It would be `true` by default (as to not create a breaking change), but, if set to `false`, value would not be changed if it was before `min` or after `max`. Then consumers could inform users that they need to correct a value using form validation rules.

**Comment by zombieJ** [comment]
Make sense.

**Comment by zombieJ** [comment]
Is that could be not use `min` and `max` but use antd Form to configure the `rules` instead?

**Comment by StefanNienhuis** [comment]
Could you clarify the issue with such a property? `min` and `max` should still be set on the actual input, it just shouldn't automatically update the value when it is invalid. Form validation should pick it up instead and warn the user.

Using `rules` could work, but giving the browser a sense of min and max values is a good practice for accessibility. In addition to that the step buttons should still be disabled when a min or max is reached.

**Comment by zombieJ** [comment]
https://github.com/react-component/input-number/pull/596  support `changeOnBlur`
