### ISSUE TITLE
在iOS系统的safari里面点击+-没反应

### ISSUE THREAD

**Issue by zysc8313** [react-component/input-number#60]

**Comment by afc163** [comment]
What your rc-input-number's version? Have you tried the latest `3.4.12`? It is working in my machine.

**Comment by zysc8313** [comment]
你好，我用的是3.4.8

**Comment by zysc8313** [comment]
3.4.12同样有问题，即使是官方demo(http://react-component.github.io/input-number/examples/simple.html), 在我的手机上查看也是一样有问题

**Comment by paranoidjk** [comment]
try 
```js
<InputNumber useTouch />
```

**Comment by zysc8313** [comment]
加上useTouch，手机端（iOS）正常，PC端不工作（需要自己判断是手机还是PC，进而设置useTouch）。组件内部有机制自动识别吗？
另外对于可以Touch也可以鼠标的设备，是不是会有问题？

**Comment by paranoidjk** [comment]
@zysc8313 

用 useTouch 来手动区分 MouseEvent 和 TouchEvent 的原因在这里 https://github.com/react-component/input-number/issues/48
如果你想在 PC 和 Mobile 同时用，就用你说的 `自己判断是手机还是PC，进而设置useTouch` 好了。
