### ISSUE TITLE
Add id attribute

### ISSUE THREAD

**Issue by nathanloisel** [react-component/input-number#62]
Hey,

If some are interested on that, I can do a pull-request, just let me know.

**Comment by benjycui** [comment]
Use case?

**Comment by nathanloisel** [comment]
https://www.w3schools.com/tags/tag_label.asp

**Comment by paranoidjk** [comment]
@nathanloisel 
do you mean you want to add `<label>` for `rc-input-number` inner `<input>`?

can you give us a PR ?

**Comment by paranoidjk** [comment]
@nathanloisel rc-input-number@3.6.0. Added `props.id`
