### ISSUE TITLE
Change Max Number to Number.MAX_SAFE_NUMBER

### ISSUE THREAD

**Issue by alexggordon** [react-component/input-number#69]
By default, I don't think the max number should be `Infinity`, as javascript will basically not handle numbers above [The Max Safe Integer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). This results in unpredictable behavior in large numbers in this component. Conversely, we should probably change the default minimum to `- MAX_SAFE_INTEGER`

If you're okay with this change I'll PR.

**Comment by paranoidjk** [comment]
LGTM，PR is welcome.

Notice that you should change doc at the same time, and this will be break change.

**Comment by paranoidjk** [comment]
cc @afc163

**Comment by afc163** [comment]
IE is not supported.

**Comment by alexggordon** [comment]
@afc163 so we could either hard-code the Max Safe Integer (check if it's defined, if not, use hard code), or just not make the change. However, there's some pretty weird behavior in the input when you get over the MSI. Thoughts?

**Comment by alexggordon** [comment]
@afc163 it looks like we can work around this super easily. Something like 

```
const MAX_SAFE_INTEGER = Number.MAX_SAFE_INTEGER || Math.pow(2, 53) - 1
```

and then just use MAX_SAFE_INTEGER in default prop types.
