### ISSUE TITLE
undefined is not an object (evaluating 'styles.container')

### ISSUE THREAD

**Issue by efournival** [react-component/input-number#71]
1. `npm install rc-input-number`
2. Added `import InputNumber from 'rc-input-number'`
3. Added `<InputNumber defaultValue={20} />`

I'm using React Native 0.45.1 and React 16.

**Comment by paranoidjk** [comment]
- https://github.com/react-component/input-number/blob/fb106183835573ab73fb3ccd3df70a094559ecc3/src/index.ios.js#L125

- https://github.com/react-component/input-number/blob/fb106183835573ab73fb3ccd3df70a094559ecc3/src/mixin.js#L19

**Comment by paranoidjk** [comment]
@efournival  You should give your rc-input-number version. And please try latest version at first.

**Comment by efournival** [comment]
I'm using the latest version:
```bash
edgar@arch:~/sources/moonapp$ npm list | grep rc-input-number
├─┬ rc-input-number@3.6.0
```

**Comment by paranoidjk** [comment]
@efournival https://github.com/react-component/input-number/blob/master/examples/react-native/demo.js#L15 See the official demo,  you must give the styles props. 

cc @afc163 maybe we should add a null/undefined check.

**Comment by efournival** [comment]
All right, I thought it could work on its own. :)
Thank you.

**Comment by yesmeck** [comment]
RN version has extract to https://github.com/react-component/m-input-number.

https://github.com/react-component/m-input-number/issues/2
