### ISSUE TITLE
mixin.js 第175行的判断导致 this.props.precision 传入值为 0 的时候无法生效

### ISSUE THREAD

**Issue by weihong1028** [react-component/input-number#72]
如题，我在使用 setFieldsValue(41.4564) 时，发现 InputNumber 组件上的 this.props.precision 无法生效，调试到该行直接把 precision 等于 0 的情况给忽略掉了，这应该是一个 bug。

**Comment by afc163** [comment]
来个 PR ！~

**Comment by benjycui** [comment]
Closed in https://github.com/react-component/input-number/pull/73
