### ISSUE TITLE
Can't set the input field as "required"

### ISSUE THREAD

**Issue by cdimitroulas** [react-component/input-number#86]
Passing required={true} as a prop does not set the required attribute in the html. This prop should be able to be passed to that the field can be marked as required and get the benefits of the browser pointing user's to the required field when they try to submit the form.

**Comment by Attrash-Islam** [comment]
I'll prepare a PR for this in the next hour 👍🏻

**Comment by Attrash-Islam** [comment]
Waiting for PR approval :)

**Comment by yutingzhao1991** [comment]
maybe you want this: https://github.com/react-component/form. rc-form provided a complete verify solution.

**Comment by Attrash-Islam** [comment]
PR got merged
