### ISSUE TITLE
Add pattern on input.

### ISSUE THREAD

**Issue by doxiaodong** [react-component/input-number#89]
Since keyboard type is decided by pattern sometimes.

More details can be found at https://developer.apple.com/library/content/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html

`inputmode` is another important attribute in the future.

**Comment by yutingzhao1991** [comment]
@doxiaodong make a pr on this?

**Comment by paulcmason** [comment]
@doxiaodong @yutingzhao1991 - Hi - I am happy to create a PR for this - the pattern attribute may also be useful for form validation.

**Comment by doxiaodong** [comment]
Thanks @paulcmason

**Comment by paulcmason** [comment]
PR submitted

**Comment by doxiaodong** [comment]
thks
