### ISSUE TITLE
interactions for adding negative value is not natural

### ISSUE THREAD

**Issue by chenyong** [react-component/input-number#91]
For adding `-0.12`, I got values in `onChange`,

```
""
"-"
0
"-0."
-0.1
-0.12
```

triggered in https://github.com/react-component/input-number/blob/master/src/index.js#L176

```js
  onChange = (e) => {
    if (this.state.focused) {
      this.inputting = true;
    }
    const input = this.props.parser(this.getValueFromEvent(e));
    this.setState({ inputValue: input });
    this.props.onChange(this.toNumberWhenUserInput(input)); // valid number or invalid string
  }
```

and numbers are parsed(or not) https://github.com/react-component/input-number/blob/master/src/index.js#L352

```js
  // '1.0' '1.00'  => may be a inputing number
  toNumberWhenUserInput(num) {
    // num.length > 16 => prevent input large number will became Infinity
    if ((/\.\d*0$/.test(num) || num.length > 16) && this.state.focused) {
      return num;
    }
    return this.toNumber(num);
  }
```

However, in my code, `value` is  replaced with `this.props.x`, so then `0` arrives, `-0` turns into `0`, we loose the character `-`:

```jsx
<InputNumber
  value={this.props.x}
  step={0.1}
  onChange={this.handleXChange.bind(this)}
/>
```

I can try a temp fix by removing `value` and adding `defaultValue`, which bypasses formatting `"-0"` into `0`. But I need a better solution of fixing the issue.

**Comment by yutingzhao1991** [comment]
I think this is a bug of input-number. should not parse string `-0` to number `0`.

A hack way to fix it: https://codesandbox.io/s/7208qn32vq

**Comment by DanHarman** [comment]
@yutingzhao1991 I tried the hack and it still has issues. e.g. If you have '-34' in the value and want to change it to '-0.34', if you start to type '0' after the minus sign, the control removes the zero before you even have a change to enter the '.'. It also moves the cursor to the end, which is another bug!

I think it is far too aggressive converting from string to number. It should be doing this when focus is lost, or validating, not in the middle of typing.

**Comment by yutingzhao1991** [comment]
@DanHarman agree! Do you want to make a PR?
