### ISSUE TITLE
Refs Must Have Owner OR Multiple copies of React loaded

### ISSUE THREAD

**Issue by PatrikMatiasko** [react-component/input-number#93]
Hi,

Thx for this package (lib).

I have one problem with you package. If I use your package in my project everything works fine, but If I build my project and then I include my package to new project you library crash my project.

Problem is: Refs Must Have Owner OR Multiple copies of React loaded. 

I can fix it, if I remove _**ref:'up**_' and _**ref: 'down'**_ in node_modules file /rc-input-number/es/index.js from Up and Down elements (lines: 424, 443). Everything will work nice. Can you change this in you package ? 

@see: 
https://reactjs.org/warnings/refs-must-have-owner.html

**Comment by yutingzhao1991** [comment]
I guess it's the problem of your project. Please check this: https://reactjs.org/warnings/refs-must-have-owner.html#multiple-copies-of-react.

**Comment by PatrikMatiasko** [comment]
It's not problem of Multiple copies of React loaded  ... its problem in ref as string. I run **_npm ls react_** and nothing bad.  (I cant find any problem with duplicity of react)

**Comment by PatrikMatiasko** [comment]
any idea ? or can be string ref replaced ... as input ref ?

**Comment by yesmeck** [comment]
Yes, we should replace string ref with ref callback.
